# - name: install vscode extensions
#   shell: code --install-extension {{ item }}
#   with_items: "{{ vscode.extensions }}"

# TODO(pbovbel) configure vscode shortcuts (copy up/down)



# gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-up "[]"
# gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-down "[]"
# gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left "[]"
# gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right "[]"