kernel_options:
  - quiet
  - splash
  - mitigations=off
  - acpi_rev_override=1
  - acpi_osi=Linux
  - nouveau.modeset=0
  - pcie_aspm=force
  - drm.vblankoffdelay=1
  - scsi_mod.use_blk_mq=1
  - nouveau.runpm=0
  - mem_sleep_default=deep

# bluez_version: "5.63"
